### PR TITLE
allow current versions of inifile, firewall, stdlib

### PR DESCRIPTION
**Pull request by kenyon**
`metadata.json` update to allow the current versions of the inifile, firewall, and stdlib modules.

### CODE REVIEW

**Comment by smortex** [comment]
@kenyon stumble here after following links from other issue… I guess you need to sigh the CLA above for this issue to be fixed?

**Review by smortex — APPROVED** [review]

**Comment by kenyon** [comment]
Still waiting on my company to allow me to sign the CLA. I think this one can fall under the trivial patch exemption though.

**Review by ekohl — APPROVED** [review]
I would think so too. There's literally no other way to do this so this feels trivial. However, not a lawyer and I don't work for Puppet.

**Comment by austb** [comment]
Yeah, sorry I was off for a little while. This PR falls under the trivial patch exemption. I'll merge it, and try to get a release out in the next few days. There are some issues with the module's CI that I'll need to resolve before the release can go out.

**Review by austb — APPROVED** [review]

**Pull request merged**
