### PR TITLE
MODULES-5123 Fixed compatibility w/ puppetlabs-postgresql 5.0.0

### PR DESCRIPTION
**Pull request by jkroepke**
https://tickets.puppetlabs.com/browse/MODULES-5123

### CODE REVIEW

**Comment by baurmatt** [comment]
`database_port` also needs to be a Integer.

**Comment by jkroepke** [comment]
@baurmatt It's not necessary, because the database_port param does't have a validator

https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/manifests/validate_db_connection.pp#L11

But if you want it, it's okay.

**Comment by baurmatt** [comment]
True, but https://github.com/puppetlabs/puppetlabs-postgresql/blob/5.0.0/manifests/server/grant.pp#L10 needs has a validation :(

**Comment by jkroepke** [comment]
@baurmatt Maybe I do not hit this error because I updated a already working puppetdb.

Thanks for the hints.

**Comment by jkroepke** [comment]
Hum, looks like test failures are not related to this issue..

**Comment by mmoll** [comment]
this should also get noted in metadata.json then, 👍 otherwise

**Comment by jkroepke** [comment]
Sure.

**Comment by mullr** [comment]
Thanks for this PR! I ended up merging a different one that did the same thing, but appreciate the contribution.

**Pull request closed without merging**
