### PR TITLE
(maint) Allow stdlib 8.0.0

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Comment by austb** [comment]
hey @smortex it appears that our Legal department rolled out a new CLA today. I was going to merge these and cut a new puppetdb module release, but (and I just double check with them) you'll need to sign the new CLA before I can merge this.

Once you're able to sign the CLA, I'll get the release done promptly. Thanks for your contributions, and sorry for the extra hoops you are having to jump through.

**Comment by smortex** [comment]
@austb done, the page was blank earlier this day when I received a dozen notifications :smiley:

**Comment by austb** [comment]
Thanks! Yeah, I heard there were some web issues early in the rollout, but I'm glad it loaded eventually for you.

**Comment by smortex** [comment]
@austb can we release a new version of the module?

Some modules cannot be updated to support stdlib 8.0.0 because they also depend on the puppetdb module which latest released version require version `< 8.0.0`?

**Pull request merged**
