### PR TITLE
Release 4.3.0 of module

### PR DESCRIPTION
**Pull request by kbarber**
This updates the CHANGELOG and the metadata.json ready for a new release.

Signed-off-by: Ken Barber <ken@bob.sh>

### CODE REVIEW

**Comment by kbarber** [comment]
Blocked on PR-135

**Comment by ajroetker** [comment]
fwiw if you build the release tarball on your machine run it with
```
COPYFILE_DISABLE=true bundle exec puppet module build
```
So that OSX won't put in a bunch of `._*` files

**Comment by kbarber** [comment]
@ajroetker I always check my module file before shipping anyway, because I trust that tool very little anyway :-).

**Comment by ajroetker** [comment]
:-D you're a wise man

**Comment by ajroetker** [comment]
lgtm from the log etc

**Pull request merged**
