### PR TITLE
Use datatype Sensitive to prevent credentials leaks.

### PR DESCRIPTION
**Pull request by camilo-schoeningh-sociomantic**

### CODE REVIEW

**Comment by austb** [comment]
I believe this might be better served by using the [Sensitive](https://puppet.com/docs/puppet/5.5/lang_data_sensitive.html) data type. Let me know if that doesn't cover your use case, I may be missing something.

**Comment by camilo-schoeningh-sociomantic** [comment]
@austb Cool! I missed that type. :+1:

**Comment by camilo-schoeningh-sociomantic** [comment]
The pr is updated.

**Comment by binford2k** [comment]
Looks like tests are failing on this. Think you could address that @camilo-schoeningh-sociomantic?

```
       error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Left match operand must result in a String value. Got a Sensitive. (file: /home/travis/build/puppetlabs/puppetlabs-puppetdb/spec/fixtures/modules/postgresql/manifests/server/role.pp, line: 127, column: 10) (file: /home/travis/build/puppetlabs/puppetlabs-puppetdb/spec/fixtures/modules/postgresql/manifests/server/db.pp, line: 41) on node travis-job-cf78c5e3-7fbd-42e7-ab4f-fcf405004c05.c.travis-ci-prod-2.internal
```

**Comment by vchepkov** [comment]
It's just Sensitive, not Sensitive[String]

**Comment by h0tw1r3** [comment]
superseded by #331

**Pull request closed without merging**
