### PR TITLE
fix incorrect year in release date

### PR DESCRIPTION
**Pull request by corporate-gadfly**

### CODE REVIEW

**Comment by kenyon** [comment]
Changelog should be automatically generated, so not sure how this would become wrong.

**Comment by corporate-gadfly** [comment]
Not that important, so closing.

**Comment by smortex** [comment]
That was fixed in 0053513364d07f0c78ade801bcdcf322abfbab18.  It looks like this changelog is crafted by hand :scream:

**Comment by corporate-gadfly** [comment]
Ahh... Makes sense, TY.

**Pull request closed without merging**
